import type { Metadata } from "next";
import "./globals.scss";

export const metadata: Metadata = {
  title: "TuRolita Oficial",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-full flex flex-col">
        <main>
         {children}
        </main>
      </body>
    </html>
  );
}
